feat(whiskers)!: switch to tera, use rich context objects
catppuccin/toolbox pull request #150
Opened 2024-03-30 13:04 UTC by backwardspy

2024-03-30 14:39 UTC, nullishamy requested changes

2024-03-30 14:39 UTC, nullishamy commented on whiskers/Cargo.toml
> +version = "2.0.0-beta.0"
Are we keeping this for release?

2024-03-30 14:39 UTC, nullishamy commented on whiskers/Cargo.toml
> +serde_json = "1.0"
Do we need both json & yaml?

2024-03-30 14:39 UTC, nullishamy commented on whiskers/Cargo.toml
> +lzma-rust = "0.1"
Is this compromised :skull:

2024-03-30 14:39 UTC, nullishamy commented on whiskers/examples/demo/output/frappe.md
> -- **alpha:**              153 / 0.60
Are these different because we actually have accurate math now, or is it a bug?

2024-03-30 14:39 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub list_functions: bool,
Should this be exclusive?

2024-03-30 14:39 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
Does whiskers print and write to disk in the case of a matrix being used? I noticed piping to a file being used in justfiles before. Might be worth clarifying this in the docs?

2024-03-30 14:39 UTC, nullishamy commented on whiskers/src/cli.rs
> +    if Path::new(s).is_file() {
Does Path::new not abort if the path is invalid? Or is that only checked if you try to use it?

2024-03-30 14:43 UTC, backwardspy commented on whiskers/Cargo.toml
> +version = "2.0.0-beta.0"
yeah i was thinking of going with a beta release to start with while we convert existing templates and add any additional missing filters & functions. might give us a slightly more obvious "this is unfinished software" sort of vibe that's missing right now 😅

2024-03-30 14:56 UTC, backwardspy commented on whiskers/Cargo.toml
> +serde_json = "1.0"
the only serialization we do with serde_json is for the output of `-l -o json`, everything else is deserialization that could presumably be done with serde_yaml. i could live without the json output if you think it's worth dropping the dependency. that said tera depends on the same version of serde_json so it might not actually save us much.

2024-03-30 14:57 UTC, backwardspy commented on whiskers/Cargo.toml
> +lzma-rust = "0.1"
pure rust port, thankfully!

2024-03-30 15:09 UTC, backwardspy commented on whiskers/examples/demo/output/frappe.md
> -- **alpha:**              153 / 0.60
definitely just me being lazy and not wanting to make another red with a slightly different opacity. fixed!

2024-03-30 15:09 UTC, nullishamy commented on whiskers/Cargo.toml
> +serde_json = "1.0"
Nah, wasn't overly concerned with reducing deps, was just curious if it was a redundant leftover :+1: .

2024-03-30 15:10 UTC, backwardspy commented on whiskers/Cargo.toml
> +version = "2.0.0-beta.0"
> Template requires whiskers version ^2.0.0, but you are running whiskers 2.0.0-beta.0
found the flaw in that plan. changed it back to 2.0.0, it'll be fine!

2024-03-30 15:16 UTC, backwardspy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
whiskers always writes to disk when a matrxi is used (unless `--dry-run` is passed), i have added some more info to the docs to make this clearer.

2024-03-30 15:18 UTC, backwardspy commented on whiskers/src/cli.rs
> +    if Path::new(s).is_file() {
as far as i can tell for a read check like this it cannot fail, but it could if i were to try to write to an invalid path for example.

2024-03-30 15:19 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
So it will always print them, and conditionally write it?

2024-03-30 15:20 UTC, backwardspy commented on whiskers/src/cli.rs
> +    pub list_functions: bool,
i've tried to emulate it with `required_unless_present = "list_functions"` on the `template` argument but it could be better. i recall having trouble with clap's argument groups last time i tried, i'll give that another go. :+1:

2024-03-30 15:22 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub list_functions: bool,
There should be an `exclusive` prop or something that makes it so you cant pass anything else with it. Just thinking it might be useful because it would clobber the output if this is also printed alongside a template? Food for thought, nothing mandatory of course.

2024-03-30 15:22 UTC, backwardspy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
i opted to never actually print the templates to stdout in this mode just due to the sheer amount of information it can produce from the combinatorial explosion of matrix options. in dry run mode it instead prints a single line per file that would be rendered with a size in bytes. outside of dry run mode it just creates the files without saying anything. love to hear alternative ideas for both cases in this mode!

2024-03-30 15:23 UTC, nullishamy commented on whiskers/src/cli.rs
> +    if Path::new(s).is_file() {
Makes sense.

2024-03-30 15:32 UTC, backwardspy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
<details>
<summary>example `--dry-run` output</summary>

```console
$ cargo run -q --bin whiskers -- multifile.tera --dry-run
Would write 45 bytes into catppuccin-latte-rosewater-normal.ini
Would write 44 bytes into catppuccin-latte-flamingo-normal.ini
Would write 40 bytes into catppuccin-latte-pink-normal.ini
Would write 41 bytes into catppuccin-latte-mauve-normal.ini
Would write 39 bytes into catppuccin-latte-red-normal.ini
Would write 42 bytes into catppuccin-latte-maroon-normal.ini
Would write 41 bytes into catppuccin-latte-peach-normal.ini
Would write 42 bytes into catppuccin-latte-yellow-normal.ini
Would write 41 bytes into catppuccin-latte-green-normal.ini
Would write 40 bytes into catppuccin-latte-teal-normal.ini
Would write 39 bytes into catppuccin-latte-sky-normal.ini
Would write 44 bytes into catppuccin-latte-sapphire-normal.ini
Would write 40 bytes into catppuccin-latte-blue-normal.ini
Would write 44 bytes into catppuccin-latte-lavender-normal.ini
Would write 47 bytes into catppuccin-frappe-rosewater-normal.ini
Would write 46 bytes into catppuccin-frappe-flamingo-normal.ini
Would write 42 bytes into catppuccin-frappe-pink-normal.ini
Would write 43 bytes into catppuccin-frappe-mauve-normal.ini
Would write 41 bytes into catppuccin-frappe-red-normal.ini
Would write 44 bytes into catppuccin-frappe-maroon-normal.ini
Would write 43 bytes into catppuccin-frappe-peach-normal.ini
Would write 44 bytes into catppuccin-frappe-yellow-normal.ini
Would write 43 bytes into catppuccin-frappe-green-normal.ini
Would write 42 bytes into catppuccin-frappe-teal-normal.ini
Would write 41 bytes into catppuccin-frappe-sky-normal.ini
Would write 46 bytes into catppuccin-frappe-sapphire-normal.ini
Would write 42 bytes into catppuccin-frappe-blue-normal.ini
Would write 46 bytes into catppuccin-frappe-lavender-normal.ini
Would write 49 bytes into catppuccin-macchiato-rosewater-normal.ini
Would write 48 bytes into catppuccin-macchiato-flamingo-normal.ini
Would write 44 bytes into catppuccin-macchiato-pink-normal.ini
Would write 45 bytes into catppuccin-macchiato-mauve-normal.ini
Would write 43 bytes into catppuccin-macchiato-red-normal.ini
Would write 46 bytes into catppuccin-macchiato-maroon-normal.ini
Would write 45 bytes into catppuccin-macchiato-peach-normal.ini
Would write 46 bytes into catppuccin-macchiato-yellow-normal.ini
Would write 45 bytes into catppuccin-macchiato-green-normal.ini
Would write 44 bytes into catppuccin-macchiato-teal-normal.ini
Would write 43 bytes into catppuccin-macchiato-sky-normal.ini
Would write 48 bytes into catppuccin-macchiato-sapphire-normal.ini
Would write 44 bytes into catppuccin-macchiato-blue-normal.ini
Would write 48 bytes into catppuccin-macchiato-lavender-normal.ini
Would write 45 bytes into catppuccin-mocha-rosewater-normal.ini
Would write 44 bytes into catppuccin-mocha-flamingo-normal.ini
Would write 40 bytes into catppuccin-mocha-pink-normal.ini
Would write 41 bytes into catppuccin-mocha-mauve-normal.ini
Would write 39 bytes into catppuccin-mocha-red-normal.ini
Would write 42 bytes into catppuccin-mocha-maroon-normal.ini
Would write 41 bytes into catppuccin-mocha-peach-normal.ini
Would write 42 bytes into catppuccin-mocha-yellow-normal.ini
Would write 41 bytes into catppuccin-mocha-green-normal.ini
Would write 40 bytes into catppuccin-mocha-teal-normal.ini
Would write 39 bytes into catppuccin-mocha-sky-normal.ini
Would write 44 bytes into catppuccin-mocha-sapphire-normal.ini
Would write 40 bytes into catppuccin-mocha-blue-normal.ini
Would write 44 bytes into catppuccin-mocha-lavender-normal.ini
Would write 58 bytes into catppuccin-latte-rosewater-no-italics.ini
Would write 57 bytes into catppuccin-latte-flamingo-no-italics.ini
Would write 53 bytes into catppuccin-latte-pink-no-italics.ini
Would write 54 bytes into catppuccin-latte-mauve-no-italics.ini
Would write 52 bytes into catppuccin-latte-red-no-italics.ini
Would write 55 bytes into catppuccin-latte-maroon-no-italics.ini
Would write 54 bytes into catppuccin-latte-peach-no-italics.ini
Would write 55 bytes into catppuccin-latte-yellow-no-italics.ini
Would write 54 bytes into catppuccin-latte-green-no-italics.ini
Would write 53 bytes into catppuccin-latte-teal-no-italics.ini
Would write 52 bytes into catppuccin-latte-sky-no-italics.ini
Would write 57 bytes into catppuccin-latte-sapphire-no-italics.ini
Would write 53 bytes into catppuccin-latte-blue-no-italics.ini
Would write 57 bytes into catppuccin-latte-lavender-no-italics.ini
Would write 60 bytes into catppuccin-frappe-rosewater-no-italics.ini
Would write 59 bytes into catppuccin-frappe-flamingo-no-italics.ini
Would write 55 bytes into catppuccin-frappe-pink-no-italics.ini
Would write 56 bytes into catppuccin-frappe-mauve-no-italics.ini
Would write 54 bytes into catppuccin-frappe-red-no-italics.ini
Would write 57 bytes into catppuccin-frappe-maroon-no-italics.ini
Would write 56 bytes into catppuccin-frappe-peach-no-italics.ini
Would write 57 bytes into catppuccin-frappe-yellow-no-italics.ini
Would write 56 bytes into catppuccin-frappe-green-no-italics.ini
Would write 55 bytes into catppuccin-frappe-teal-no-italics.ini
Would write 54 bytes into catppuccin-frappe-sky-no-italics.ini
Would write 59 bytes into catppuccin-frappe-sapphire-no-italics.ini
Would write 55 bytes into catppuccin-frappe-blue-no-italics.ini
Would write 59 bytes into catppuccin-frappe-lavender-no-italics.ini
Would write 62 bytes into catppuccin-macchiato-rosewater-no-italics.ini
Would write 61 bytes into catppuccin-macchiato-flamingo-no-italics.ini
Would write 57 bytes into catppuccin-macchiato-pink-no-italics.ini
Would write 58 bytes into catppuccin-macchiato-mauve-no-italics.ini
Would write 56 bytes into catppuccin-macchiato-red-no-italics.ini
Would write 59 bytes into catppuccin-macchiato-maroon-no-italics.ini
Would write 58 bytes into catppuccin-macchiato-peach-no-italics.ini
Would write 59 bytes into catppuccin-macchiato-yellow-no-italics.ini
Would write 58 bytes into catppuccin-macchiato-green-no-italics.ini
Would write 57 bytes into catppuccin-macchiato-teal-no-italics.ini
Would write 56 bytes into catppuccin-macchiato-sky-no-italics.ini
Would write 61 bytes into catppuccin-macchiato-sapphire-no-italics.ini
Would write 57 bytes into catppuccin-macchiato-blue-no-italics.ini
Would write 61 bytes into catppuccin-macchiato-lavender-no-italics.ini
Would write 58 bytes into catppuccin-mocha-rosewater-no-italics.ini
Would write 57 bytes into catppuccin-mocha-flamingo-no-italics.ini
Would write 53 bytes into catppuccin-mocha-pink-no-italics.ini
Would write 54 bytes into catppuccin-mocha-mauve-no-italics.ini
Would write 52 bytes into catppuccin-mocha-red-no-italics.ini
Would write 55 bytes into catppuccin-mocha-maroon-no-italics.ini
Would write 54 bytes into catppuccin-mocha-peach-no-italics.ini
Would write 55 bytes into catppuccin-mocha-yellow-no-italics.ini
Would write 54 bytes into catppuccin-mocha-green-no-italics.ini
Would write 53 bytes into catppuccin-mocha-teal-no-italics.ini
Would write 52 bytes into catppuccin-mocha-sky-no-italics.ini
Would write 57 bytes into catppuccin-mocha-sapphire-no-italics.ini
Would write 53 bytes into catppuccin-mocha-blue-no-italics.ini
Would write 57 bytes into catppuccin-mocha-lavender-no-italics.ini
```

</details>

2024-03-30 15:40 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
Cool, seems reasonable. Curious other question - does the matrix stuff check for files existing before trying to write to them? Just thinking about dx here wrt debugging / inspecting the produced output of templates with matrix stuff enabled.

2024-03-30 15:41 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub list_functions: bool,
Reasonable. This is fine for now, can tweak later if we want!

2024-03-30 15:45 UTC, backwardspy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
right now it just blindly overwrites, somewhat mimicking the behaviour of piping single-file whiskers into a file. the `--check` flag works in matrix mode for some debugging/inspecting use-cases (though i'd like to improve it, it currently exits on the first changed file) but i would certainly not mind locking that overwriting behaviour behind another flag to make it opt-in.

2024-03-30 17:32 UTC, nullishamy commented on whiskers/src/cli.rs
> +    pub dry_run: bool,
I think we can circle back to this once we've played around more with matrix in the real world. Current behaviour fine for the first iteration!

2024-03-30 17:32 UTC, nullishamy approved these changes
Lets get this merged!

2024-03-31 14:46 UTC, sgoudham approved these changes
Glanced over the PR, found no glaring issues and docs have been updated. Can't wait for this to be rolled out across the organisation.

Absolutely _stellar_ work @backwardspy, and @nullishamy for the productive feedback.

2024-03-31 14:52 UTC, merged