feat: write results to `filename` in single file mode
catppuccin/toolbox pull request #218
Opened 2024-05-16 11:28 UTC by uncenter

Now writes the results of single file templates to `whiskers.filename` if present, like in matrix mode.

2024-05-18 00:10 UTC, sgoudham requested changes
I think it'd be good to update the `justfiles` in the [single-file](https://github.com/catppuccin/toolbox/tree/main/whiskers/examples/single-file) directory as part of this PR.

2024-05-18 20:33 UTC, sgoudham requested changes

2024-05-18 20:33 UTC, sgoudham commented on whiskers/src/main.rs
> -        } else {
I believe there's a regression here:

This if statement is not present in the extracted `write_template` function defined above.

2024-05-19 20:38 UTC, nullishamy commented on whiskers/src/main.rs
> +    check: bool,
Any particular reason to change these? Seems like it would be more useful to have them wrapped in the struct?

2024-05-19 21:44 UTC, nullishamy approved these changes
LGTM, seems to have conflicts? Can get those fixed and then this is good for merge :+1:

2024-05-19 21:53 UTC, uncenter commented
Ah yeah it was the trailing newlines I fixed in my last PR. Should be good now.

2024-05-22 16:34 UTC, nullishamy approved these changes

2024-05-22 17:58 UTC, backwardspy approved these changes

2024-05-23 16:35 UTC, sgoudham approved these changes

2024-05-23 16:36 UTC, merged