perf(catwalk): Use custom anti-aliasing
catppuccin/toolbox pull request #32
Opened 2023-08-08 19:03 UTC by DakshG07

Custom anti-aliasing probably had the biggest effect here, but there's been a multitude of changes made.

Performance improvments:
- Custom anti-aliasing
- Calculates inverse-slope once for efficiency
- Improved algorithm for calculating inverse slope
- Less data needs to be passed to TrapMask
- Removes unnecessary masking, builds image directly

Other improvements:
- More doc comments in mask.rs
- gen_mask now uses the supplied aa_level for all images (fix)
- Renames img to image in RoundMask for consistency

While the custom anti-aliasing isn't perfect, I tried to get a result as close to the original as possible:
![image](https://github.com/catppuccin/toolbox/assets/48651837/a1157c54-5d7e-433e-bcdd-1b2bccbc59e3)
![image](https://github.com/catppuccin/toolbox/assets/48651837/368d0646-4ffd-4206-a304-5ea9c48d9c39)
Custom algorithm on the left, old algorithm on the right.

And, of course, we're seeing about a 2x improvement in performance:
```
Benchmark 1: target/release/catwalk-aa assets/latte.webp assets/frappe.webp assets/macchiato.webp assets/mocha.webp
  Time (mean ± σ):      5.691 s ±  0.128 s    [User: 4.586 s, System: 1.101 s]
  Range (min … max):    5.511 s …  5.961 s    10 runs

Benchmark 2: target/release/catwalk assets/latte.webp assets/frappe.webp assets/macchiato.webp assets/mocha.webp
  Time (mean ± σ):      2.533 s ±  0.136 s    [User: 2.383 s, System: 0.148 s]
  Range (min … max):    2.371 s …  2.820 s    10 runs

Summary
  target/release/catwalk assets/latte.webp assets/frappe.webp assets/macchiato.webp assets/mocha.webp ran
    2.25 ± 0.13 times faster than target/release/catwalk-aa assets/latte.webp assets/frappe.webp assets/macchiato.webp assets/mocha.webp
```

2023-08-09 17:39 UTC, nekowinston commented on Cargo.toml
> -
Is this change intentional?

2023-08-09 17:42 UTC, nekowinston requested changes
Haven't checked it locally yet, just some comments

2023-08-09 17:42 UTC, nekowinston commented on catwalk/src/mask.rs
> +                //res.mask_alpha(&mask.bands().3);
Let's use git instead of comments here...
```suggestion
```

2023-08-09 17:42 UTC, nekowinston commented on catwalk/src/mask.rs
> +        //res.mask_alpha(&mask.bands().3);
Same here
```suggestion
```

2023-08-09 18:10 UTC, DakshG07 commented on Cargo.toml
> -
Probably not.

2023-08-10 14:35 UTC, nekowinston approved these changes
Thanks for improving this! 🚀 
I actually prefer the look of the new AA, I think.

Benchmarks on the VSCode assets, with default options, on my M1 Max MacBook:
```
Benchmark 1: ./catwalk latte.webp frappe.webp macchiato.webp mocha.webp
  Time (mean ± σ):      3.458 s ±  0.011 s    [User: 3.158 s, System: 0.293 s]
  Range (min … max):    3.446 s …  3.483 s    10 runs

Benchmark 2: ./catwalk-pr latte.webp frappe.webp macchiato.webp mocha.webp
  Time (mean ± σ):      1.619 s ±  0.005 s    [User: 1.566 s, System: 0.050 s]
  Range (min … max):    1.613 s …  1.627 s    10 runs

Summary
  ./catwalk-pr latte.webp frappe.webp macchiato.webp mocha.webp ran
    2.14 ± 0.01 times faster than ./catwalk latte.webp frappe.webp macchiato.webp mocha.webp
```

2023-08-10 14:36 UTC, merged